typography_spectrum: 0.25
color:
  brandColors:
    - '#ffffff'
    - '#393834'
    - '#a5a7a6'
    - '#5d5e60'
    - '#d7d4cf'
  brandStrength: 0.6875
  lightness: 0.7744903564453125
  saturation: 0.4423568155616522
  rhythmicContrast: 0.6512319922912866
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Commute
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Whats up dude?
    id: c07f6914-4a79-449c-a5a6-fd9908daaa52
    type: content
favicon: null
title: Aim Shoot Reflect
description: There is time 2&from work
purpose: []
